#!/bin/sh

. /lib/functions.sh

board=$(board_name)
gpio=525

case "$board" in
devolo,dlan-pro-1200plus-ac)
	echo 0 > /sys/class/gpio/gpio${gpio}/value
	sleep 1
	echo 1 > /sys/class/gpio/gpio${gpio}/value
	;;

*)
	echo "$0: unknown board $board" >&2
	exit 1;
	;;
esac
